version: "2"

services:

  jenkins:
    image: mario21ic/jenkins:docker
    build:
      context: ./docker/jenkins/
    volumes:
      - ./data/jenkins/:/var/jenkins_home/
      - ./logs/jenkins/:/var/log/jenkins/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - 8080:8080
    command: --prefix=/jenkins

  nginx:
    image: nginx:1.11
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - jenkins
    ports:
      - 80:80
