version: "2"

services:

  jenkins:
    image: jenkins:2.60.1
    volumes:
      - ./data/jenkins/:/var/jenkins_home/
      - ./logs/jenkins/:/var/log/jenkins/
    #ports:
    #  - 8080:8080
    command: --prefix=/jenkins

  nginx:
    image: nginx:1.11
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - jenkins
    ports:
      - 80:80
